Part1.4
MadaraMO/FSO pull request #2
Opened 2020-09-21 12:26 UTC by MadaraMO

Man 1.4. joprojām strādā arī šādi, taču neesmu izpildījusi Tavus ieteikumus, piemēram, Header bug neesmu atkodusi (es varētu gan vēl papētīt pati!) un īsti neesmu destrukturējusi kodu (ko es arī labprāt vēl izdarītu!), bet laiks iet, un tāpēc es PR - tur būs visai daudz commitu, sākumā es biju iekūlusies maldu ceļos.  Es vēlos pie tā pasēdēt vēl, bet laiks iet uz priekšu, un varbūt man noderēs vēl kāds Tavs komentārs vai atkārtota norāde uz to pašu, ko jau esi reiz teicis.

2020-09-21 14:34 UTC, joltmode requested changes
Ar PR vispār ir tā, ka tev vajag viņu māsterī iedabūt. Tādēļ jau viņš tiek pieteikts.

Tā ideja ir:

- start with `master`
  - create a `feature` branch
  - do your updates
  - PR
  - work on solving the PR if any change requests come... (turpinot komitot un pushot tajā pašā brenčā)
  - to, ultimately, get PR approved for merge into `master`
- now locally, checkout to `master` and pull - it now has the changes (_and potentially any other changes from other developers who went on with their tasks while you worked on yours_)
  - create a `feature` branch
  - ...

Baigi neuztraucies, ka tev nesanāk steigšus PR dabūt gaisā. 

Uz tiem uzdevumiem kuri ir FSO pirmajā nodaļā, kā jau pati teici, ka **a** & **b** & **c** jau esi muļļājusi un tev izteikti jauns būtu **d**, kā reiz ieieties pareizā PR flowā būtu svarīgāk.

Tagad es skatos, ka tu esi uzņēmusi noti katru uzdevumu laist savā PR. Tā arī nevajadzētu. Es nezinu kur ir tas sweetspots ar FSO, bet nu domāju, ka liekam upper limitu pilnu nodaļu. Ja es redzēšu, ka ir daudz izmaiņas un būs vēl jūra vienas nodaļas ietvaros, tad pie PR procesa vienosimies, ka laižam māsterī un sāksi jaunu PR.

Ja sanāk, ka tev viens PR ir gatavs, es neesmu paspējis izskatīt un tu jau gribi darboties pie nākamajiem uzdevumiem, tad padod man zināt Slack'ā (man tā ir vienīgā quick-attention vide), uztaisi tēju/ielej ūdeni/kafiju, ja es nepaspēju atbildēt, tad jauno uzdevumu daļu atvasini no tā brenča kuru laidi iekš pirmā PR, veic savas izmaiņas pa virsu un taisīsi PR uz iepriekšējo feature branču.

Un! **PR izmaiņu rekvests ir tavs prioritārākais uzdevums. Anything else can wait.**

2020-09-21 14:34 UTC, joltmode commented on part1/src/index.js
> +  ]
Tu tagad esi datus izcēlusi ārpus `App`, kas nebija prasīts uzdevumā. Tādēļ arī bagu nevar novērot. 😁  Tu skaisti danco viņam apkārt!

2020-09-21 14:36 UTC, joltmode commented
Tagad es skatos, ka 1.5 uzdevumu laid tepat. Sākot ar 1.6 jau viss baigi mainīsies un tam būs jauns PR, kuru drošvien laidīsim iekšā līdz ar pirmās nodaļas beigām.

2020-09-21 14:39 UTC, joltmode commented
> [..] Es vēlos pie tā pasēdēt vēl, bet laiks iet uz priekšu [..]

Es teiktu, ka tad nesarežģī savu apmācību procesu, mēģinot ātrāk dabūt kaut kādus rezultātus. Lēnām, bet pamatīgi! 🙂 

Man nav nekādas ekspektācijas un prasības, izņemot to, ka es gribu, lai stabili apgūsti šīs lietas.

2020-09-25 15:45 UTC, joltmode approved these changes
Un gatavs ar ir! 👍 

Saprati par scope / komponentēm / propiem?

2020-09-25 15:52 UTC, MadaraMO commented
Šķiet, ka sapratu :) Interesanti tagad atskatīties uz to, kā es centos visu sarežģīt. Un man izdevās! Visu sarežģīt. Tagad redzu, cik daudz jēdzīgāka ir secīga problēmu risināšana.

2020-09-25 15:53 UTC, merged