Part 2
MadaraMO/FSO pull request #5
Opened 2020-10-02 07:50 UTC by MadaraMO

Masīvu metodes, komponenšu pārnešana citās direktorijās un mazliet arī stili. Saziņa ar serveri un formas, šķiet, būs vissarežģītākais.

2020-10-06 12:33 UTC, MadaraMO commented
Exercise 2.4. with comments 

/// atstāju komentāros redzamu to, ka vēlējos izmantot Total komponenti (zem Content komentāru daļā `part={part.exercises} key={part.id}).`  ir vispār uz ātru roku uzmests). Diemžēl tas neatšķetinājās. 
Kļūda:  parts.reduce neesot funkcija. 

**Redzu, ka šodien neesi slackā, tāpēc atļaušos te pasēdēt un padomāt pati, un tad turpināt ar šo uzdevumu tālāk, jo atliek tikai:

2020-10-06 13:35 UTC, joltmode requested changes

2020-10-06 13:35 UTC, joltmode commented on part2/src/index.js
> +</>
Ja atgriez tikai vienu elementu, fragmentu (`<>`) apkārt nevajag.

2020-10-06 13:35 UTC, joltmode commented on part2/src/index.js
> +    </>
Šeit var ar fragmentu, kas nav slikti, jo labi nes meaningu, bet [React (JSX) pieļauj arī atgriezt komponenšu masīvu](https://reactjs.org/docs/jsx-in-depth.html#jsx-children:~:text=A%20React%20component%20can%20also%20return%20an%20array%20of%20elements%3A), līdz ar to varētu arī maukt: `return parts.map(part => <Part /**/ />)` ;)

Just saying, manuprāt no koda sapratnes viedokļa šādā gadījumā ar fragmentu ir labāk.

P.S. Paskaties kopumā to linku, tur visādi interesanti patterni.

2020-10-08 13:46 UTC, joltmode approved these changes

2020-10-08 13:48 UTC, merged